#!/usr/bin/env zsh

export TERM='rxvt-256color'
export DOTFILES="$HOME/.dotfiles"

# XDG
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_CACHE_HOME=$HOME/.cache

# editor
export EDITOR="vim"
export VISUAL="vim"

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zsh_history" # History filepath
export HISTSIZE=10000                   # Maximum events for internal history
export SAVEHIST=10000                   # Maximum events in history file

# Set the configuration file for Starship prompt
export STARSHIP_CONFIG=$HOME/.config/starship/starship.toml

# Define the installation path for Zinit
export ZINIT_HOME="$XDG_DATA_HOME/zinit/zinit.git"