import = [
  "~/.config/alacritty/themes/themes/nord.toml"
]

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
decorations = "None"

[font]
normal = { family = "BlexMono Nerd Font Mono", style = "Medium" }
size = 12.0

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"
